### ISSUE TITLE
Too many lines on the output

### ISSUE THREAD

**Issue by netcriptus** [rudolfce/SQLi_bruteforce#2]
It would be really nice to see less lines on the output. I mean, I get it, the fact that you're presenting all the combinations that were tried and output the combinations. But how about you use [only one line for that](http://stackoverflow.com/questions/517127/how-do-i-write-output-in-same-place-on-the-console), formatting the output?

This way we might have a hollywood-like tool.

**Comment by rudolfce** [comment]
That would be nice indeed. Will be working on it soon. Thanks for the suggestion.

**Comment by rudolfce** [comment]
"Soon" took quite some time, didn't it?

I liked it.
